// <auto-generated />
using System;
using MessageService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageService.Data.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteMessageDbContext))]
    [Migration("20260903013354_AddGroupMemberCount")]
    partial class AddGroupMemberCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MessageService.Models.AnonymousIdentity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("GroupId", "Label")
                        .IsUnique();

                    b.ToTable("AnonymousIdentities");
                });

            modelBuilder.Entity("MessageService.Models.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastMessageAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PictureContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureFetchedUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PictureUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MessageService.Models.GroupMember", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureFetchedUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PictureUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("MessageService.Models.GroupMemberPicture", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("GroupId", "UserId");

                    b.ToTable("GroupMemberPictures");
                });

            modelBuilder.Entity("MessageService.Models.GroupMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StickerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageType")
                        .HasFilter("\"MessageType\" = 'sticker'");

                    b.HasIndex("WebhookEventId")
                        .IsUnique();

                    b.HasIndex("GroupId", "EventTimestamp");

                    b.HasIndex("GroupId", "Id");

                    b.ToTable("GroupMessages");
                });

            modelBuilder.Entity("MessageService.Models.GroupPicture", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("GroupId");

                    b.ToTable("GroupPictures");
                });

            modelBuilder.Entity("MessageService.Models.HighlightKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyToAllGroups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HighlightKeywords");
                });

            modelBuilder.Entity("MessageService.Models.HighlightKeywordGroup", b =>
                {
                    b.Property<int>("HighlightKeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("HighlightKeywordId", "GroupId");

                    b.ToTable("HighlightKeywordGroups");
                });

            modelBuilder.Entity("MessageService.Models.HighlightUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HighlightUsers");
                });

            modelBuilder.Entity("MessageService.Models.HostHeartbeat", b =>
                {
                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptionKeyFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OutboxOldestAgeSeconds")
                        .HasColumnType("REAL");

                    b.Property<long?>("OutboxPending")
                        .HasColumnType("INTEGER");

                    b.HasKey("Role", "MachineName");

                    b.ToTable("HostHeartbeats");
                });

            modelBuilder.Entity("MessageService.Models.MaskKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ApplyToAllGroups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaskKeywords");
                });

            modelBuilder.Entity("MessageService.Models.MaskKeywordGroup", b =>
                {
                    b.Property<int>("MaskKeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("MaskKeywordId", "GroupId");

                    b.ToTable("MaskKeywordGroups");
                });

            modelBuilder.Entity("MessageService.Models.MessageContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClaimedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DownloadStatus")
                        .HasFilter("\"DownloadStatus\" <> 'Completed'");

                    b.HasIndex("GroupMessageId")
                        .IsUnique();

                    b.ToTable("MessageContents");
                });

            modelBuilder.Entity("MessageService.Models.MessageContentBlob", b =>
                {
                    b.Property<long>("MessageContentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("MessageContentId");

                    b.ToTable("MessageContentBlobs");
                });

            modelBuilder.Entity("MessageService.Models.UserAlias", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserAliases");
                });

            modelBuilder.Entity("MessageService.Models.ViewerSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaskLandline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaskMobilePhone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaskNationalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaskNhiCard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameDisplayMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ViewerSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaskLandline = true,
                            MaskMobilePhone = true,
                            MaskNationalId = true,
                            MaskNhiCard = false,
                            NameDisplayMode = "Original",
                            RetentionDays = 1095
                        });
                });

            modelBuilder.Entity("MessageService.Models.GroupMemberPicture", b =>
                {
                    b.HasOne("MessageService.Models.GroupMember", "GroupMember")
                        .WithOne("Picture")
                        .HasForeignKey("MessageService.Models.GroupMemberPicture", "GroupId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMember");
                });

            modelBuilder.Entity("MessageService.Models.GroupPicture", b =>
                {
                    b.HasOne("MessageService.Models.Group", "Group")
                        .WithOne("Picture")
                        .HasForeignKey("MessageService.Models.GroupPicture", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MessageService.Models.HighlightKeywordGroup", b =>
                {
                    b.HasOne("MessageService.Models.HighlightKeyword", "HighlightKeyword")
                        .WithMany("Groups")
                        .HasForeignKey("HighlightKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HighlightKeyword");
                });

            modelBuilder.Entity("MessageService.Models.MaskKeywordGroup", b =>
                {
                    b.HasOne("MessageService.Models.MaskKeyword", "MaskKeyword")
                        .WithMany("Groups")
                        .HasForeignKey("MaskKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaskKeyword");
                });

            modelBuilder.Entity("MessageService.Models.MessageContent", b =>
                {
                    b.HasOne("MessageService.Models.GroupMessage", "GroupMessage")
                        .WithOne("Content")
                        .HasForeignKey("MessageService.Models.MessageContent", "GroupMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMessage");
                });

            modelBuilder.Entity("MessageService.Models.MessageContentBlob", b =>
                {
                    b.HasOne("MessageService.Models.MessageContent", "MessageContent")
                        .WithOne("Blob")
                        .HasForeignKey("MessageService.Models.MessageContentBlob", "MessageContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageContent");
                });

            modelBuilder.Entity("MessageService.Models.Group", b =>
                {
                    b.Navigation("Picture");
                });

            modelBuilder.Entity("MessageService.Models.GroupMember", b =>
                {
                    b.Navigation("Picture");
                });

            modelBuilder.Entity("MessageService.Models.GroupMessage", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("MessageService.Models.HighlightKeyword", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MessageService.Models.MaskKeyword", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("MessageService.Models.MessageContent", b =>
                {
                    b.Navigation("Blob");
                });
#pragma warning restore 612, 618
        }
    }
}
